export * from './ngx-jsonapi.module';
export * from './interfaces';
export { Autoregister } from './decorators/autoregister';
export { Core as JsonapiCore } from './core';
export { Resource } from './resource';
export { DocumentResource } from './document-resource';
export { DocumentCollection } from './document-collection';
export { Service } from './service';
export { setJsonapiInjector, JsonapiInjector } from './services/jsonapi-injector';
export { HttpClient } from '@angular/common/http';
